### ISSUE TITLE
Identical paths in different databases can't be serialized

### ISSUE THREAD

**Issue by Bosdongen** [kamsar/Rainbow#1]
When I use this configuration in unicorn this an error is thrown.
```
<predicate type="Unicorn.Predicates.SerializationPresetPredicate, Unicorn" singleInstance="true">
   <include database="core" path="/sitecore/system/Settings" />
   <include database="master" path="/sitecore/system/Settings" />
</predicate>
```
**Throws this error**
```
Multiple predicate include nodes had the same name 'Settings'. This is not allowed. Note that this can occur if you did not specify the name attribute and two include entries end in an item with the same name. Use the name attribute on the include tag to give a unique name.
```

**Comment by kamsar** [comment]
From the error message:

"Note that this can occur if you did not specify the name attribute and two include entries end in an item with the same name. Use the name attribute on the include tag to give a unique name."

If no name is specified, the include name becomes the last segment in the path - in this case `Settings`.

You should make one, or both, of the includes something like `<include name="Core Settings" database="core" path="/sitecore/system/Settings" />`
