### ISSUE TITLE
Cannot serialize element

### ISSUE THREAD

**Issue by haliphax** [kamsar/Rainbow#22]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Unicorn fails to serialize `/sitecore/system/Settings/Rules/Definitions/Elements/Engagement Automation/Visibility/GeoIP visibility`

**If the current behavior is a bug, please provide the steps to reproduce.**
Create a Unicorn config that includes `/sitecore/system/Settings` from the `master` database. Serialize. Sync.

**What is the expected behavior?**
That `/sitecore/system/Settings/Rules/Definitions/Elements/Engagement Automation/Visibility/GeoIP visibility` would be serialized without error

**Please mention your Sitecore version, Rainbow version, and if also using Unicorn, your version of that too.**
Sitecore 8.2 (rev. 161221), Rainbow 1.4.1.0, Unicorn 3.3.2.0.

**Comment by haliphax** [comment]
````1 error occurred during deserialization. Earlier log messages for items below should be ignored; an error occurred that was retried and failed to correct.
master:/sitecore/system/Settings/Rules/Definitions/Elements/Engagement Automation/Visibility/GeoIP visibility (f5f82952-6d03-402a-a781-fc78c9880046)
c:\inetpub\sitecore\data\Unicorn\My Site\Master settings\Settings\Rules\Definitions\Elements\Engagement Automation\Visibility\GeoIP visibility.yml
> InvalidOperationException: Unable to compare Rule field due to invalid XML value.
> XmlException: The 'rule' start tag on line 2 position 4 does not match the end tag of 'Regel'. Line 9, position 5.

For full stack traces of each exception, see the Sitecore logs.````

**Comment by haliphax** [comment]
Fixed with an update to the latest version of `Rainbow` NuGet packages. Not sure if this bug report should stand or not.

**Comment by kamsar** [comment]
This was fixed as you found in those latest Rainbow packages. The fix explicitly passes invalid XML through to the serialized item (this item ships in Sitecore with an invalid value that appears to be a translation error, as 'Regel' is Danish for 'rule' according to @cassidydotdk).
