### ISSUE TITLE
$Name adding $ in TFS

### ISSUE THREAD

**Issue by amitthakur2014** [kamsar/Rainbow#4]
Hi,
We are having branch template with $Name and with new version of Unicorn it get seriliazed as $Name.yaml and when try to add this in TFS it give error special character are allowed in TFS.

In Previous version of unicorn the $Name used to get serialized to %40Name.item and it is used to get added easily in TFS

**Comment by kamsar** [comment]
This is a relatively trivial fix to make ([here](https://github.com/kamsar/Rainbow/blob/master/src/Rainbow/Storage/SerializationFileSystemTree.cs#L533)) to add $ to what `Path.GetInvalidFileNameChars()` returns, however that trivial fix would also invalidate branch templates that are currently serialized by folks _not_ using TFS and cause them to get deleted (I'm pretty sure).

So the options seem to be either:
* We make the trivial fix and instruct people to reserialize after upgrade - which is suboptimal as many upgraders will probably miss that tidbit and get their branches deleted
* We add some sort of special case to the name resolution to check for existing $ names and use them if they exist (could be slow)
* We make a configuration setting by which you can add your own explicit invalid item name characters and instruct folks using TFS to add `$` to that setting

I'm leaning towards the last option.

Tagging @WizX20 as reporter of the same issue on Unicorn.

**Comment by WizX20** [comment]
The last option sounds good to me. I would be happy to implement this if you could point me in the right direction.

**Comment by kamsar** [comment]
@WizX20 essentially you'd add some extra characters to the code linked in my last comment, and read it from a config file using `Settings.GetStringSetting()` (iirc), using a default value of empty string.

Then you'd add a config file that sets it - say `Rainbow.TFS.config.disabled` and include it in the nuspec file like the `Rainbow.config` is.

**Comment by kamsar** [comment]
This has been implemented and will be released in the next Rainbow version.
